CC=clang
LDFLAGS=-lSDL2 -L. -llibfbxc -L.
CFLAGS=-Wall -Wno-pragma-pack -ISDL2-2.0.9\include -Iinclude\glad -Iinclude
BINARY=engine

ifeq ($(OS),Windows_NT)
	BINARY:=$(BINARY).exe
endif

engine: main.o glad.o engine2D.o
	$(CC) -o $(BINARY) $(LDFLAGS) $^

glad.o: glad.c include\glad\glad.h
	$(CC) -c -o $@ $(CFLAGS) $<

engine2D.o: engine2D.c engine2D.h
	$(CC) -c -o $@ $(CFLAGS) $<

main.o: main.c
	$(CC) -c -o $@ $(CFLAGS) $^